---
version: "3"

services:
  fm-dashboard:
    container_name: fm_dashboard
    image: fm-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./raw_data:/data